### ISSUE TITLE
Use Vagrant for provisioning a Centos 7 VM and install Docker

### ISSUE THREAD

**Issue by alesr** [ProjectRocket/provision#1]
Implement a Makefile for managing the environment and Ansible for installing Docker.

**Comment by alesr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [S0 - Create "provision" repo and use Vagrant to create a Centos7 VM with Docker installed](https://trello.com/c/rDEKO50W/14-s0-create-provision-repo-and-use-vagrant-to-create-a-centos7-vm-with-docker-installed)

**Comment by h314to** [comment]
Working on it!
