### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by h314to** [ProjectRocket/provision#3]
I get the following message:

`TASK [copy SSH key to node] ****************************************************
failed: [controller] (item=192.168.10.2) => {"changed": true, "cmd": ["sshpass", "-p", "vagrant", "ssh-copy-id", "-i", "/home/vagrant/.ssh/id_rsa.pub", "-o", "StrictHostKeyChecking=no", "vagrant@192.168.10.2"], "delta": "0:02:07.678152", "end": "2017-01-19 16:18:44.647229", "failed": true, "item": "192.168.10.2", "rc": 1, "start": "2017-01-19 16:16:36.969077", "stderr": "mktemp: failed to create file via template ‘/root/.ssh/ssh-copy-id_id.XXXXXXXXXX’: No such file or directory\nmktemp failed", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [controller] (item=192.168.10.3) => {"changed": true, "cmd": ["sshpass", "-p", "vagrant", "ssh-copy-id", "-i", "/home/vagrant/.ssh/id_rsa.pub", "-o", "StrictHostKeyChecking=no", "vagrant@192.168.10.3"], "delta": "0:02:07.514205", "end": "2017-01-19 16:20:52.774051", "failed": true, "item": "192.168.10.3", "rc": 1, "start": "2017-01-19 16:18:45.259846", "stderr": "mktemp: failed to create file via template ‘/root/.ssh/ssh-copy-id_id.XXXXXXXXXX’: No such file or directory\nmktemp failed", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @/Users/agapito/Development/ProjectRocket/provision/provision/playbooks/provision.retry

PLAY RECAP *********************************************************************
controller                 : ok=4    changed=3    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

**Comment by alesr** [comment]
@h314to Please list the version of your Ansible, Vagrant and Virtual Box

**Comment by alesr** [comment]
```
Ansible 2.2.1.0
Vagrant 1.8.6
Virtual Box 5.1.12
```

**Comment by h314to** [comment]
Ansible  2.2.0.0
Vagrant 1.9.1
Virtual Box 5.1.12 r112440

**Comment by alesr** [comment]
We need to change the Vagrantfile to boot the managed nodes before the controller so the controller can copy the ssh key to the managed node
